name: Build

on: 
   push:
      branches:
      - 'workflow'

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Build Unity project
           uses: webbertakken/unity-builder@v0.10
           env:
               UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
           with:
              projectPath: .
              unityVersion: 2019.2.11f1
              targetPlatform: StandaloneWindows
