name: Build

on: 
   push:
      branches:
      - 'workflow'

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Clone Unity project
           uses: actions/checkout@v2
           with:
              lfs: true
         - name: Build Unity project
           uses: webbertakken/unity-builder@v0.10
           env:
               UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
           with:
              projectPath: .
              unityVersion: 2019.2.11f1
              targetPlatform: StandaloneWindows
         - name: Upload artifacts
           uses: actions/upload-artifact@v1
           with:
            name: Build
            path: build

         - name: Download artifacts
           uses: actions/download-artifact@v2
           with: 
               name: Build
